show user -- whoami

show con_name -- list Container DB

show pdbs -- list Pluggable DB


SET TERMOUT OFF -- To spool output generated by commands in a script without displaying the output on the screen

-- SPOOL: redirect to file: https://docs.oracle.com/en/database/oracle/oracle-database/23/sqpug/SPOOL.html

