show user -- whoami

show con_name -- list Container DB

show pdbs -- list Pluggable DB


SET TERMOUT OFF; -- To spool output generated by commands in a script without displaying the output on the screen

-- SPOOL: redirect to file: https://docs.oracle.com/en/database/oracle/oracle-database/23/sqpug/SPOOL.html


SELECT NAME, VALUE
FROM v$parameter
where ISSYS_MODIFIABLE != 'FALSE';
-- list system value



-- verify TrueCache : If CURRENT_SCN is advancing over time, it means that True Cache is moving forward as expected.
SELECT database_role, open_mode, current_scn FROM v$database;
