name: oracle
services:
  db:
    container_name: oracledb
    image: container-registry.oracle.com/database/free
    environment:
      - ORACLE_PWD=password
      - ORACLE_SID=FREE # 23c default
    ports:
      - 1521:1521