# TODO WIP
name: oracle
services:
  primary:
    container_name: primary
    image: container-registry.oracle.com/database/free
    environment:
      - ORACLE_PWD=password
      - ORACLE_SID=FREE # 23c default
      - ENABLE_ARCHIVELOG=true # required for true-cache
      - ENABLE_FORCE_LOGGING=true # required for true-cache
    ports:
      - 1521:1521
    # volumes:
    #   - ./true-cache-log:/opt/oracle/oradata
  true-cache:
    container_name: true-cache
    image: container-registry.oracle.com/database/free
    ports:
      - 1521
    environment:
      - TRUE_CACHE=true
      - PRIMARY_DB_PWD_FILE=/var/tmp/orapwFREE
      - PRIMARY_DB_CONN_STR=primary:1521/FREE
    # volumes:
    #   - ./true-cache-log:/opt/oracle/oradata
    depends_on:
      primary:
        condition: service_healthy