-- grant permission
-- TODO: not enough for ADB data actions
GRANT CREATE ANY ANALYTIC VIEW TO ADMIN;
GRANT CREATE ANY ATTRIBUTE DIMENSION TO ADMIN;
GRANT CREATE ANY HIERARCHY TO ADMIN;
GRANT DROP ANY ANALYTIC VIEW TO ADMIN;
GRANT DROP ANY ATTRIBUTE DIMENSION TO ADMIN;
GRANT DROP ANY HIERARCHY TO ADMIN;

